---
# defaults file for vagrant-cape
mongodb_version: 5.0
mongodb_repo_key: "https://www.mongodb.org/static/pgp/server-{{ mongodb_version }}.asc"

mongodb_db_main_path: /data
mongodb_db_paths:
  - "{{ mongodb_db_main_path }}/db"
  - "{{ mongodb_db_main_path }}/configdb"

# postgres
postgres_version: 13
postgres_repo_key: https://download.postgresql.org/pub/repos/apt/ACCC4CF8.asc


# yara
yara_repo_rul: https://github.com/VirusTotal/yara.git
yara_release_version: 4.1.0
yara_source_code_dir: "/tmp/yara-v{{ yara_release_version }}"
yara_default_install_dir: /usr/local/bin/
yara_python_repo_url: https://github.com/VirusTotal/yara-python
yara_python_source_code_dir: "/tmp/yara-python-v{{ yara_release_version }}"
yara_config_options:
  - enable-cuckoo
  - enable-magic
  - enable-dotnet
  - enable-profiling